### PR TITLE
bump - dependencies

### PR DESCRIPTION
**Pull request by codecog**
Update of dependencies to provide node 12 support.

### CODE REVIEW

**Comment by nurettintopal** [comment]
@ancashoria any updates on this PR?

**Comment by ancashoria** [comment]
@nurettintopal sorry for the delay, I'm trying to merge it now, but there are conflicts due to previously merged PR.
Can you fix them?
I will publish afterwards.

Thanks

**Comment by ancashoria** [comment]
I have updated the dependencies in another commit.

**Comment by ancashoria** [comment]
Please check if v0.3.0 is working for you. Thanks

**Comment by nurettintopal** [comment]
@ancashoria it works fine, thank you! 🎉

**Pull request closed without merging**
